id: I45382217
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T13:57:22+00:00'
last_modified: '2022-06-08T07:11:20.448528+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4PD2014
  title: 'དམ་ཆོས་དགོངས་པ་གཅིག་པའི་ཀར་ཊཱིཀ་ཆེན་མོ།

    '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7E7E:
      image_group_id: I2PD20585
      title: ''
      total_pages: 440
      order: 1
      base_file: 7E7E.txt
    826E:
      image_group_id: I2PD20586
      title: ''
      total_pages: 418
      order: 2
      base_file: 826E.txt
    F208:
      image_group_id: I2PD20587
      title: ''
      total_pages: 532
      order: 3
      base_file: F208.txt
    66A2:
      image_group_id: I2PD20588
      title: ''
      total_pages: 562
      order: 4
      base_file: 66A2.txt
    C4CC:
      image_group_id: I2PD20589
      title: ''
      total_pages: 470
      order: 5
      base_file: C4CC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
