id: I45382217
legacy_id: P006836
ocr_import_info:
  bdrc_scan_id: W4PD2014
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T13:53:40'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:16:36.970428+00:00'
last_modified: 2022-09-04 05:17:56.867150
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4PD2014
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4PD2014
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་ཆོས་དགོངས་པ་གཅིག་པའི་ཀར་ཊཱིཀ་ཆེན་མོ།
  author: ཀརྨ་པ ༠༨་མི་བསྐྱོད་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.961063645001778
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I2PD20589:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20589
      total_pages: 470
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I2PD20589.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9598136053431424
    legacy_id: v005
  I2PD20587:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20587
      total_pages: 532
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2PD20587.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9614592352372645
    legacy_id: v003
  I2PD20586:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20586
      total_pages: 418
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2PD20586.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9617523974473959
    legacy_id: v002
  I2PD20588:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20588
      total_pages: 562
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I2PD20588.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9603188593060127
    legacy_id: v004
  I2PD20585:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2PD20585
      total_pages: 440
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2PD20585.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9623308593742718
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
