id: P006836
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:46.699944
source_metadata:
  id: bdr:W4PD2014
  title: 'དམ་ཆོས་དགོངས་པ་གཅིག་པའི་ཀར་ཊཱིཀ་ཆེན་མོ།

    '
  author: ''
  volumes:
    76c4d2030f7048e49842488acacc17de:
      image_group_id: I2PD20585
      title: ''
      volume_number: 1
      total_pages: 440
      base_file: v001.txt
    1f15b0a97d4247118ce2d095a5ef7477:
      image_group_id: I2PD20586
      title: ''
      volume_number: 2
      total_pages: 418
      base_file: v002.txt
    7eab89123f7a4c91b7401ac67cb4ff16:
      image_group_id: I2PD20587
      title: ''
      volume_number: 3
      total_pages: 532
      base_file: v003.txt
    899905bf2e8b4b96a8277b672f80abd4:
      image_group_id: I2PD20588
      title: ''
      volume_number: 4
      total_pages: 562
      base_file: v004.txt
    867ca603be6f4a01b4c58468e9369e29:
      image_group_id: I2PD20589
      title: ''
      volume_number: 5
      total_pages: 470
      base_file: v005.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
